### PR TITLE
Informatívnejšia správa pri detekcii príslušnosti študenta.

### LINKED ISSUE #218: Informatívnejšia správa pri detekcii príslušnosti študenta
Ak sa nenadetekuje správna príslušnosť študenta, dostane vypísanú hlášku "V ankete môžu hlasovať iba študenti ...".

Nastávajú problémy, ak sú záznamy v AIS2 chybné - konkrétne sa stáva, že pri študijnom programe chýba "Akreditujúca OJ" v aplikácii VSST030 v záložke "Program UIPŠ". Potom zápisný list ostane bez priradenia fakulte a študenti, dostávajú neinformatívnu hlášku.

Navrhovaná zmena: vypísať v hláške všetky nadetekované študijné programy zo zápisných listov a súčasne aj ich priradenia fakúlt, ak zápisný list nemá priradenie fakulty, vypísať "bez fakulty".

Príklad: Nadetekované študijné programy: INF (FMFI) mGL-DG (bez fakulty)

### PR DESCRIPTION
**Pull request by Sameth**
Pokiaľ študentovi nie je dovolené hlasovať, zobrazí sa mu zoznam
evidovaných zápisných listov (kód programu, org. jednotka).

Fixes #218

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/anketa/243)

### CODE REVIEW

**Comment by Sameth** [comment]
Aktualne zmeny sa daju pozriet v anketaarene "sameth", kde je user "petrucha2" nastaveny tak, aby hitol tuto upravenu hlasku.

Snad netreba mat AISovy cookie, ak by bolo treba, funkcnu ukazku asi musime robit osobne (alebo sa casovo dohodnut; prihlasenia trvaju velmi kratko).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/243#-:-KqNzuO-3t6CAmUVzhX6:bonohnr)*

**Comment by mrshu** [comment]
Vo vseobecnosti moze byt, rozbehol som to s mojou cookie, zafungovalo myslim celkom slusne (vid obrazok nizsie). Myslim, ze uz staci iba vycistit a mozeme mergnut.



---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/AnketaBundle/Controller/AbstractVotingController.php, line 33 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/243#-KqSouTwuxRQbrWTWkXX:-KqSouTxlHll5BOyc82X:bl0b5ek) ([raw file](https://github.com/fmfi-svt/anketa/blob/657f444d55ab211343622981c1d627af65dbb04f/src/AnketaBundle/Controller/AbstractVotingController.php#L33)):*
> ```PHP
>             }
>             $retriever = $this->get('anketa.ais_retriever');
>             $result = $retriever->getResult("Neexistujuci_nazov_fakulty", $semestre);
> ```

Verim, ze `Neexistujuci_nazov_fakulty` sa v buducnosti zmeni na cosi relevantnejsie

---

*[src/AnketaBundle/Integration/votr_runner.py, line 40 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/243#-KqSpE17iu6NQWmeLei9:-KqSpE17iu6NQWmeLeiA:b-jd9s2b) ([raw file](https://github.com/fmfi-svt/anketa/blob/657f444d55ab211343622981c1d627af65dbb04f/src/AnketaBundle/Integration/votr_runner.py#L40)):*
> ```Python
>                     if zapisny_list.akademicky_rok in relevantne_roky:
>                         toto_studium = {}
>                         if studium.sp_skratka: toto_studium['skratka'] = studium.sp_skratka
> ```

Chapem, ze za takto skratenym `if`/`else` moze byt snaha o skratenie nie prilis potrebneho kodu, ale v takomto pripade by som asi skor preferoval bud

```python
toto_studium['skratka'] = studium.sp_skratka if studium.sp_skratka else "Neznamy program"
```

alebo este kratsie (ale zasa menej citatelnejsie/priamociarejsie)

```python
toto_studium['skratka'] = studium.sp_skratka or "Neznamy program"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/243#-:-KqSsr0__NwlISP1Yriu:b1gz1ee)*

**Comment by Sameth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/AnketaBundle/Controller/AbstractVotingController.php, line 33 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/243#-KqSouTwuxRQbrWTWkXX:-KqTArYeEBBgTUoCbnBF:b-k5lh9v) ([raw file](https://github.com/fmfi-svt/anketa/blob/657f444d55ab211343622981c1d627af65dbb04f/src/AnketaBundle/Controller/AbstractVotingController.php#L33)):*
<details><summary><i>Previously, mrshu (Marek Šuppa) wrote…</i></summary><blockquote>

Verim, ze `Neexistujuci_nazov_fakulty` sa v buducnosti zmeni na cosi relevantnejsie
</blockquote></details>

Done.
Phew, hrabat sa v starom symfony, ktory ma hlupejsie API od novsieho, bola sranda.

---

*[src/AnketaBundle/Integration/votr_runner.py, line 40 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/243#-KqSpE17iu6NQWmeLei9:-KqTAkVGHKXKzuEORpvq:bs81cka) ([raw file](https://github.com/fmfi-svt/anketa/blob/657f444d55ab211343622981c1d627af65dbb04f/src/AnketaBundle/Integration/votr_runner.py#L40)):*
<details><summary><i>Previously, mrshu (Marek Šuppa) wrote…</i></summary><blockquote>

Chapem, ze za takto skratenym `if`/`else` moze byt snaha o skratenie nie prilis potrebneho kodu, ale v takomto pripade by som asi skor preferoval bud

```python
toto_studium['skratka'] = studium.sp_skratka if studium.sp_skratka else "Neznamy program"
```

alebo este kratsie (ale zasa menej citatelnejsie/priamociarejsie)

```python
toto_studium['skratka'] = studium.sp_skratka or "Neznamy program"
```

</blockquote></details>

Done.
Zvolil som si druhu moznost vzhladom na to, ako ten skript vyzera cely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/243)*

**Comment by mrshu** [comment]
Vdaka za updaty, :lgtm:!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/243#-:-KqUgRb8uSiDrxkwFYCm:buhotjb)*

**Comment by mrshu** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/243)*

**Pull request merged**
