### PR TITLE
Prerobene hviezdicky

### PR DESCRIPTION
**Pull request by Foxiy**
Prerobeny sprite len na 2 druhy hviezdiciek

Signed-off-by: Ondrej <o.jariabka@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/anketa/226)

### CODE REVIEW

**Comment by Foxiy** [comment]
@Adman @Sameth @mrshu Pomylil som sa s prvym spritom. Je pravda ze to bolo myslene ze budu len dva tipy hviezdiciek takze prerobil som ten sprite malo by to byt teraz lepsie.

**Comment by Sameth** [comment]
Co sa mi teraz trochu nepaci je, ze on-mouseover neviem rozoznat, ci je tato hviezdicka oznacena, alebo nie.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/226#-:-KYnOH4r449dfwiOsav5:b21bfmv)*

**Comment by Foxiy** [comment]
@Sameth @Adman @mrshu Skusil som fixnut pripomienky s mouseover. Je to lepsie takto?

**Comment by Sameth** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/226#-:-KYrtbPtGAATGWSw5wys:bnfp4nl)*

**Comment by Sameth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/226)*

**Comment by Adman** [comment]
lgtm

**Pull request merged**
