### PR TITLE
Dorobene rozne vypisy a pocitania pri roznych importoch.

### LINKED ISSUE #235: Tiché zlyhania v importoch
Keď už nás to raz pohrýzlo, je čas z toho spraviť issue a nechať ju tu, kým sa to neskontroluje a nevyrieši. 

Momentálne to vyzerá tak, že niektoré importy si len tak preskakujú niektoré záznamy a nedávajú o tom vedieť. Zišlo by sa teda pozrieť všetky importy a poprirábať minimálne nejaké alerty na to, že sa niečo nepodarilo.

### PR DESCRIPTION
**Pull request by Sameth**
Fixes #235

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/anketa/242)

### CODE REVIEW

**Comment by tvinar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/242)*

**Comment by mrshu** [comment]
@Sameth toto vo vseobecnosti vyzera dobre, len neviem uplne, ako otestujem, ci to aj dobre funguje. Mohol by si mi prosim napisat nejaky kratky navod?

Vdaka!

PS: ak takyto eyeball review pre zmenu ako je tato staci, kludne to proste mergni -- moze byt, ze chcem cosi, na com stravis vela casu, aj ked to nieje treba.

**Comment by Sameth** [comment]
Snad bude stacit eyeball review? Ak som sa sekol niekde v syntaxi, tak to vyhubuje akonahle to budeme chciet pouzit a nebude to moc narocne objavit, inac by to malo robit to, co povodne, len s drobnymi vypismi navyse.

Ako by sa to dalo otestovat:

Znamky by som cakal, ze nepojdu vobec kvoli osobnym udajom (Robilo sa toto vobec niekedy? Chceme to odstranit?).

Import katedier vyzaduje nejaku uzasnu AISovu rolu na "spravu ciselnikov". Ak budeme otvarat anketu pre LFUK, asi by bolo fajn zistit, ci sa k tomu vie vobec niekto dostat. Ked sa niekomu podari ziskat to spravne CSV, zvysok je krok 3 z importov.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/242#-:-KqSz7oHCzlnFxr2PknI:b-xeq0py)*

**Comment by mrshu** [comment]
@sameth Vdaka, that's good enough for me -- otestujeme v produkcii =)

:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/242#-:-KqUgvJemFM0M5F7xrAX:b-gsiyz2)*

**Pull request merged**
