### PR TITLE
Response: Stranka s listingom vsetkych odpovedi

### PR DESCRIPTION
**Pull request by mrshu**
Signed-off-by: mr.Shu <mr@shu.io>

--------------------------------------------

@Sameth mozes sa prosm ta na toto pozriet?

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/anketa/224)

### CODE REVIEW

**Comment by Sameth** [comment]
Vyzera to celkom dobre, co som si vsimol pri rychlom prekuknuti:

1: umiestnenie (okomentovane na vsetkych miestach): Tematicky sa mi viac hodi do /vysledky/{slug}/list, nez /odpovede/ (tam je napr. aj "moje_komentare").

2: Pridat polozku do menu nalavo. S tym suvisi aj otazka, kto vsetko to ma/moze vidiet (toto chcem skonzultovat aj s Vinkom).

Casom sa pozriem aj viac do detailov.

---

Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/AnketaBundle/Resources/config/response_routing.yml, line 26 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/224#-KpV9touFygx8UnwPjiN:-KpV9touFygx8UnwPjiO:b-hpxc04) ([raw file](https://github.com/fmfi-svt/anketa/blob/4331168109d699f4073ea0e770e6561abd0f4e69/src/AnketaBundle/Resources/config/response_routing.yml#L26)):*
> ```YAML
> 
> responses_list:
>     pattern: /odpovede/{season_slug}/list
> ```

s/odpovede/vysledky/

---

*[src/AnketaBundle/Resources/translations/messages.sk.yml, line 209 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/224#-KpVCV11FxczvZUD0kJL:-KpVCV11FxczvZUD0kJM:b-b7hv16) ([raw file](https://github.com/fmfi-svt/anketa/blob/4331168109d699f4073ea0e770e6561abd0f4e69/src/AnketaBundle/Resources/translations/messages.sk.yml#L209)):*
> ```YAML
>   list:
>     moje_komentare: Moje komentáre
>     komentare: Zoznam pridaných komentárov
> ```

Na zvazenie: "Zoznam vsetkych (pridanych) komentarov", na vyznamove odlisenie od "Zoznam (mojich) pridanych komentarov".

---

*[src/AnketaBundle/Resources/translations/routes.en.yml, line 62 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/224#-KpV7wsCd4fQJVEdjZnw:-KpV7wsCd4fQJVEdjZnx:b-1x5l1) ([raw file](https://github.com/fmfi-svt/anketa/blob/4331168109d699f4073ea0e770e6561abd0f4e69/src/AnketaBundle/Resources/translations/routes.en.yml#L62)):*
> ```YAML
> 
> # Desc: /responses/{season_slug}/list
> responses_list: '/responses/{season_slug}/list'
> ```

s/responses/results/ (vid slovenske).

---

*[src/AnketaBundle/Resources/translations/routes.sk.yml, line 65 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/224#-KpV13xOmHO26hMsThAQ:-KpV100WX-SDGO0Lpyyr:b-hpxc04) ([raw file](https://github.com/fmfi-svt/anketa/blob/4331168109d699f4073ea0e770e6561abd0f4e69/src/AnketaBundle/Resources/translations/routes.sk.yml#L65)):*
> ```YAML
> 
> # Desc: /odpovede/{season_slug}/list
> responses_list: '/odpovede/{season_slug}/list'
> ```

s/odpovede/vysledky/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/224#-:-KpV9xzLTncgynDrE8Sr:b-xzbomu)*

**Comment by Sameth** [comment]
Medzicasom som pozrel zvysne, vyzera to super!

---

Reviewed 2 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/AnketaBundle/Controller/ResponseController.php, line 93 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/224#-KpWVGnCwYqEzeE2_aDm:-KpWVGnD1yJsMmCUkfzJ:b-qx8gmp) ([raw file](https://github.com/fmfi-svt/anketa/blob/4331168109d699f4073ea0e770e6561abd0f4e69/src/AnketaBundle/Controller/ResponseController.php#L93)):*
> ```PHP
>         $seasonRepo = $em->getRepository('AnketaBundle\Entity\Season');
>         $access = $this->get('anketa.access.statistics');
>         $user = $access->getUser();
> ```

Trochu nitpick a na zvazenie: tento $user sa pouziva iba na posunutie do volania dalej; tento riadok inlinovat?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/224#-:-KpWZMkk29BOsx1V-HXp:bcxplp5)*

**Comment by Adman** [comment]
Tento PR tu je uz celkom dlho. Je este nejaka sanca, ze by sme tuto feature mergli?

**Comment by mrshu** [comment]
@Adman vacsou otazkou sa mi skor zda, ci je to vobec treba/ci to doda akusi hodnotu? Lebo to uz naozaj po tych dvoch rokoch tazko posudit... :)

**Comment by Adman** [comment]
@mrshu Keby to bolo dostupne aj pre studentov, mohlo by im to mozno ukazat, ze ucitelia odpovedaju.

**Comment by mrshu** [comment]
@Adman co teda s tymto? Skusime tomu dat este nejakych par chvil a dostat to do produkcie?

**Comment by Adman** [comment]
@mrshu ja by som bol za. V stredu sa mozme na to pozriet a otestovat na arene + mergnut.

**Comment by mrshu** [comment]
@Adman ked uz to teraz bude povinne, mozno by nebolo najhorsie tento PR zresuscitovat :)

**Comment by Adman** [comment]
@mrshu Urcite, a zverejnit ten listing pre vsetkych studentov pridanim linku do menu

**Comment by Adman** [comment]
@mrshu Myslim, ze po zvazeni nitpickov od @Sameth to mozme mergnut. Chces to fixnut, alebo to spravim ja?

**Comment by Adman** [comment]
@mrshu @tvinar Pridal som do menu link na vsetky komentare a spravil som ujednotenie prekladov. Ponechal som povodnu route na `/odpovede/slug/list`, kedze aj komentare ucitela su pod `/odpovede/`.
Co sa tyka viditelnosti, tak som ponechal, ze kazdy vidi tieto odpovede. Otestoval som to na arene -> po reviewi mozme mergnut

**Comment by mrshu** [comment]
@Adman vdaka, ze si to pofixoval -- zda sa mi to uz relativne slusne.

Za mna to kludne releasni :)

**Pull request merged**
