### PR TITLE
Added ability to expand one subject into multiple

### LINKED ISSUE #236: Expanzia preddefinovanych predmetov
V niektorych anketach by sa hodilo spravit "expanziu" predmetov, ktore by boli dopredu definovane. Teda v AISe by mal clovek predmet "Predmet" ale v configu by mohlo byt nieco v zmysle:

```
Predmet:
  - Predmet 1
  - Predmet 2
  - Predmet 3
```

a teda namiesto predmetu "Predmet" sa vytvoria predmety "Predmet 1", "Predmet 2" a "Predmet 3" (s ucitelmi nastavenymi tak, ako mali byt nastaveni v "Predmet").

### PR DESCRIPTION
**Pull request by vidriduch**
* Added new value `expand_subjects` to `config.yml` into anketa.ais_user_source
which should specify subjects (based on their long code) that should be split
into multiple subjects and is defined in `config_local.yml`.
Each entry should contain new long code for the subject as well as new name of
the subject.

* In votr_runner.py we check if the subject is in list `expand_subjects`
and if so we multiply it based on this array defined in `config_local.yml`
If the subject was expanded we also add to subjects structure a value containing
its "old" name and code. This value is None if it is a normal subject.

* `AISRetriver` just obtains this new value passed from `AISUserSource` and
sends it into `runVotr()` function where this value is passed to `votr_runner.py`

* AISUserSource recieves this value from from `config.yml` passes it first to
`AISRetriver` and then if the results are concerning student it loads all
necessary subjects including the new ones added in `votr_runner.py`. These new
subjects are first added to all "Subject" tables and then Teacher-New_Subject
pairs are added to `TeachersSubjects` tables based on the "old" name and code
values send from `votr_runner` with expanded subjects.

* Should close #236 

Signed-off-by: Ondrej Jariabka <o.jariabka@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/anketa/237)

### CODE REVIEW

**Comment by mrshu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/AnketaBundle/Integration/AISRetriever.php, line 29 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/237#-KmY7pRgBPuWF230LYwz:-KmY7pRgBPuWF230LYx-:b3g6e97) ([raw file](https://github.com/fmfi-svt/anketa/blob/adca10d77d08928647e0a34e131b94ccab0509e3/src/AnketaBundle/Integration/AISRetriever.php#L29)):*
> ```PHP
>     }
> 
>     public function getResult($fakulta = null, array $semestre = null, $expend_subjects = null) {
> ```

Not a big deal, but the last argument should probably be called `expand_subjects` instead of `expand_subjects`.

---

*[src/AnketaBundle/Integration/votr_runner.py, line 77 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/237#-KmYBkEd74JfuuiCq6KX:-KmYBkEehbcZ2trtpkb7:b-klltnh) ([raw file](https://github.com/fmfi-svt/anketa/blob/adca10d77d08928647e0a34e131b94ccab0509e3/src/AnketaBundle/Integration/votr_runner.py#L77)):*
> ```Python
>                             studijnyProgram=dict(skratka=studium.sp_skratka,
>                                                  nazov=studium.sp_popis),
>                             expanded_from_vals=None
> ```

It may be just me, but `expanded_from_vals` does not seem like 

---

*[src/AnketaBundle/Security/AISUserSource.php, line 54 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/237#-KmY8GY_kZZJUzJCfl0u:-KmY8GYaUhFlcMW67mUt:bycg280) ([raw file](https://github.com/fmfi-svt/anketa/blob/adca10d77d08928647e0a34e131b94ccab0509e3/src/AnketaBundle/Security/AISUserSource.php#L54)):*
> ```PHP
>     public function __construct(Connection $dbConn, EntityManager $em, AISRetriever $aisRetriever,
>             SubjectIdentificationInterface $subjectIdentification, $allowedOrgUnit, $checkOrgUnit,
>             LoggerInterface $logger = null, $expand_subjects)
> ```

Since the second to last argument has a default value, so should probably the final one. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/237)*

**Comment by mrshu** [comment]
Only very small nitpics, overall this looks quite good!

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/237#-:-KmYCUFpqJbCufZmE54j:b-ylx4ov)*

**Comment by mrshu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/AnketaBundle/Integration/votr_runner.py, line 77 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/237#-KmYBkEd74JfuuiCq6KX:-KmYCa_EKtMsbhbXgqkl:bulfa60) ([raw file](https://github.com/fmfi-svt/anketa/blob/adca10d77d08928647e0a34e131b94ccab0509e3/src/AnketaBundle/Integration/votr_runner.py#L77)):*
> It may be just me, but expanded_from_vals does not seem like

Yeah, does not seem like the correct name for this. I believe `expanded_from` would be good enough -- in my view `_vals` does not add much value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/237)*

**Comment by vidriduch** [comment]
@mrshu I reformatted the names. Can you please take another look at it?

**Comment by mrshu** [comment]
@vidriduch looks good, thanks, this should be ready to get merged at the right time.

**Comment by Sameth** [comment]
My 5 cents: Should this even go into master? It seems its only use will be in LFUK side branch.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/237#-:-KpVDckBmBarF8Muwev7:bwian2d)*

**Comment by mrshu** [comment]
@Sameth I do agree and thus I have created a new branch where this PR is now pointed to.

**Pull request merged**
