### PR TITLE
Fix ticheho preskakovania zlyhanych zaznamov 

### PR DESCRIPTION
**Pull request by Sameth**
Pocas importu ucitelov-predmetov

Touto zmenou sa bude do konzoly vypisovat aspon nieco o tom, ake zaznamy sa nepodarilo spracovat.
Niektore detaily sa po konzultacii mozu pomenit.

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/anketa/234)

### CODE REVIEW

**Comment by mrshu** [comment]
Za mna bez vacsich problemov, iba nejake male nitpicky. Kludne sa na ne vykasli a mergni si to, ak uznas za vhodne.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/AnketaBundle/Command/ImportUcitelPredmetCommand.php, line 86 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-KkQ5mkHnvVuBiYL5qK9:-KkQ5mkIQPEZkrSy0DoT:bkb9g7h) ([raw file](https://github.com/fmfi-svt/anketa/blob/a355fd108fb6d69b1eda6773f4067aae636b9e3e/src/AnketaBundle/Command/ImportUcitelPredmetCommand.php#L86)):*
> ```PHP
> 
>         $rows = 0;
>         $rows_success = 0;
> ```

Zda sa, ze v ankete (alebo specialne v `src/AnketaBundle/Command/` sa skor pouziva camelCase ako podtrhovniky. Nieje to nejaky velky problem, ale asi by bolo dobre skusit byt konzistentny.

---

*[src/AnketaBundle/Command/ImportUcitelPredmetCommand.php, line 107 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-KkQ6Lz1NR-8hpbJPEso:-KkQ6Lz1NR-8hpbJPEsp:b-6n9goc) ([raw file](https://github.com/fmfi-svt/anketa/blob/a355fd108fb6d69b1eda6773f4067aae636b9e3e/src/AnketaBundle/Command/ImportUcitelPredmetCommand.php#L107)):*
> ```PHP
> 
>                 if (strlen($aisNazov) == 0) {
>                     $output->writeln($aisDlhyKod . ': Chýba meno predmetu');
> ```

Nezda sa mi, ze by sa v Ankete nejako moc pouzivala diakritika, ale chapem, ze toto bude asi vystup, ktory sa bude niekam posielat, takze to dava zmysel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-:-KkQ6h2d6Mni50Y1dcDq:bwz7wtc)*

**Comment by Sameth** [comment]
Tak som pofixoval, co som nasiel. Heh, v uprave query bol pomerne zasadny bug, snad uz nic dalsie neni.

Btw, v arene som testoval, ci hentaky update (v insert query) funguje a tvari sa, ze hej.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/AnketaBundle/Command/ImportUcitelPredmetCommand.php, line 86 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-KkQ5mkHnvVuBiYL5qK9:-KkgGsNNkPGzgDrLW8TW:b-896fix) ([raw file](https://github.com/fmfi-svt/anketa/blob/a355fd108fb6d69b1eda6773f4067aae636b9e3e/src/AnketaBundle/Command/ImportUcitelPredmetCommand.php#L86)):*
<details><summary><i>Previously, mrshu (Marek Šuppa) wrote…</i></summary><blockquote>

Zda sa, ze v ankete (alebo specialne v `src/AnketaBundle/Command/` sa skor pouziva camelCase ako podtrhovniky. Nieje to nejaky velky problem, ale asi by bolo dobre skusit byt konzistentny.
</blockquote></details>

Done.

---

*[src/AnketaBundle/Command/ImportUcitelPredmetCommand.php, line 107 at r1](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-KkQ6Lz1NR-8hpbJPEso:-KkgGt3NWqDFgnb1E-we:b-tu7np) ([raw file](https://github.com/fmfi-svt/anketa/blob/a355fd108fb6d69b1eda6773f4067aae636b9e3e/src/AnketaBundle/Command/ImportUcitelPredmetCommand.php#L107)):*
<details><summary><i>Previously, mrshu (Marek Šuppa) wrote…</i></summary><blockquote>

Nezda sa mi, ze by sa v Ankete nejako moc pouzivala diakritika, ale chapem, ze toto bude asi vystup, ktory sa bude niekam posielat, takze to dava zmysel.
</blockquote></details>

Hej, toto sa planuje posielat, navyse mena, ktore tam chcem pre lepsie trackovatelne hlasky tiez vypisovat, su s diakritikou a hentak by to vyzeralo hlupo. Nieze by to v novej uprave vyzeralo uzasne (hlavne s poslednymi dvomi riadkami v anglictine), ale... 
well, spravit to kulturne by vyzadovalo cas a hrabanie sa v moznostiach Symfony.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-:-KkgHGmIZEd9OqYQumjr:b-e228be)*

**Comment by mrshu** [comment]
Diki moc, :lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/AnketaBundle/Command/ImportUcitelPredmetCommand.php, line 90 at r2](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-KkgLQ7m3fo2HWi5Ci_k:-KkgLQ7nJu_oLvbsmldt:b-utuj6f) ([raw file](https://github.com/fmfi-svt/anketa/blob/460efb1b192478cdc513960a7698b2ff167cabd2/src/AnketaBundle/Command/ImportUcitelPredmetCommand.php#L90)):*
> ```PHP
>                     FROM User a, Subject b
>                     WHERE a.login = :login and b.slug = :slug
>                     ON DUPLICATE KEY UPDATE trainer=1");
> ```

Jezkove voci, toto bol hodne velky miss z mojej strany -- sorry. Presne pre toto by tieto testy chcelo integracne testovat, co sa teda viac menej robi v arene, tazke velka vdaka, ze si to skusal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-:-KkgLzK0dU4MlCizKnIe:b4umcln)*

**Comment by mrshu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/AnketaBundle/Command/ImportUcitelPredmetCommand.php, line 90 at r2](https://reviewable.io:443/reviews/fmfi-svt/anketa/234#-KkgLQ7m3fo2HWi5Ci_k:-KkgM86OQmBSZ5WB1kp1:bg7igkv) ([raw file](https://github.com/fmfi-svt/anketa/blob/460efb1b192478cdc513960a7698b2ff167cabd2/src/AnketaBundle/Command/ImportUcitelPredmetCommand.php#L90)):*
<details><summary><i>Previously, mrshu (Marek Šuppa) wrote…</i></summary><blockquote>

Jezkove voci, toto bol hodne velky miss z mojej strany -- sorry. Presne pre toto by tieto testy chcelo integracne testovat, co sa teda viac menej robi v arene, tazke velka vdaka, ze si to skusal.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/234)*

**Pull request merged**
