### PR TITLE
frontend: Pridane nove hviezdicky

### PR DESCRIPTION
**Pull request by mrshu**
Signed-off-by: mr.Shu <mr@shu.io>

---
This change is [Reviewable](https://reviewable.io/reviews/fmfi-svt/anketa/225)

### CODE REVIEW

**Comment by Sameth** [comment]
Nechce mat ta mouseover hviezdicka rovnaky okraj ked je modra, ako ked nie je modra (cize rovnako, ked je "on", ako ked je "off")?
A non-mouseover hviezdicka ma byt realne taka priesvitna? Nieze by som sa do designu nejako moc vyznal, ale nebude to budit dojem, ze "este som vlastne toto hviezdickove hodnotenie neriesil"?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/225#-:-KYfLLifQFL6QfQlJhbz:b-dk59f)*

**Comment by mrshu** [comment]
@sameth vsetko dobre komentare, v zasade s nimi suhlasim.

Osobne sa do deisgnu nevyznam vobec, len som zmenil sprite, co mi bol poslany.

@Foxiy mozes s tymto nieco robit?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/225#-:-KYh3n59pYa4i9a71LyZ:bvq4ogf)*

**Comment by Sameth** [comment]
LGTM
Vyzera to lepsie, ale nie je to uplne to, co som mal na mysli. Kazdopadne suhlasim s tym, ze to chceme spustit a mat aspon nejake nove hviezdicky, mozme si pozriet, ako to vyzera v praxi (co je lepsie ako testovanie na produkcnom servri?).

Co som mal na mysli ja su nasledovne 2 pointy: 
1. Border na hviezdickach, ked na ne prideme mysou, je hruby a velmi vyrazny, pokial ide o "neoznacenu" hviezdicku (cize to, co sa nemeni), ale po oznaceni je taky... Meh. Mozno to je fajn (zvyrazni to rozdiel medzi oznacenymi a neoznacenymi hviezdickami).
2. Nie su oznacene (nove modre) hviezdicky prilis nevyrazne, pokial nad nimi nevisime mysou? Opat, stoji za pozretie, ako to vyzera v praxi a mozeme si aj pockat na feedback od pouzivatelov (aspon uvidime, aky je hodnotny :D )

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/225#-:-KYkGO_7Yf2MBTZnetKR:b3dedw2)*

**Comment by Sameth** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fmfi-svt/anketa/225)*

**Pull request merged**
